# 1. Create a 3x3x3 array with random values 

In [11]:
import numpy as np
arr=np.random.random((3,3,3))
print(arr)

[[[0.72746928 0.03063946 0.55441925]
  [0.08598513 0.72567547 0.60667131]
  [0.1425436  0.39836654 0.00811185]]

 [[0.79532119 0.79586406 0.31967266]
  [0.45491868 0.67769103 0.22062866]
  [0.9135298  0.784521   0.42712454]]

 [[0.98540264 0.76832343 0.72583317]
  [0.04765927 0.90779493 0.49872142]
  [0.6860576  0.96592613 0.33701821]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [68]:

arr1=np.eye(5,5)
arr1[1:,0]=1
arr1[2:,1]=2
arr1[3:,2]=3
arr1[4:,3]=4
print(arr1)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [1. 2. 3. 1. 0.]
 [1. 2. 3. 4. 1.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [45]:
arr2=np.zeros((8,8))
arr2[1::2,::2]=1
arr2[::2,1::2]=1
print(arr2)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [71]:
x=np.random.random((5,5))
print("original array:")
print(x)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print("after normalizatin:")
print(x)

original array:
[[0.66572218 0.20275399 0.25939843 0.82447633 0.67889669]
 [0.1284138  0.95745676 0.29377797 0.18479574 0.65411462]
 [0.22109493 0.33650611 0.57097801 0.97339574 0.26901542]
 [0.61080076 0.96895027 0.70186459 0.47870678 0.9026347 ]
 [0.4777267  0.50548155 0.52128683 0.72669623 0.37496428]]
after normalizatin:
[[0.6358815  0.08797844 0.15501472 0.82376025 0.65147297]
 [0.         0.9811369  0.19570143 0.06672562 0.62214445]
 [0.10968416 0.24626836 0.52375582 1.         0.16639601]
 [0.57088434 0.99473898 0.67865449 0.41455677 0.91625734]
 [0.41339689 0.44624356 0.46494844 0.70804168 0.29178196]]


# 5.  How to find common values between two arrays?

In [74]:
arr4=np.array([1,2,3,4])
print(arr4)
arr5=np.array([5,2,3,7])
print(arr5)
print(np.intersect1d(arr4,arr5))



[1 2 3 4]
[5 2 3 7]
[2 3]


# 6.How to get the dates of yesterday, today and tomorrow?

In [82]:
import numpy as np
yesterday=np.datetime64('today')-np.timedelta64(1)
print("Yesterday=",yesterday)
today=np.datetime64('today')
print("Today=",today) 
tomorrow=np.datetime64('today')+np.timedelta64(1)
print("Tomorrow=",tomorrow)                       

Yesterday= 2020-07-24
Today= 2020-07-25
Tomorrow= 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [85]:
arr4=np.random.randint(0,2,6)
print(arr4)
arr5=np.random.randint(0,2,6)
print(arr5)
array_equal=np.allclose(arr4,arr5)
print(array_equal)

[0 0 1 0 0 1]
[0 1 0 1 1 0]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [87]:
y=np.random.random(10)
print('original array:')
print(y)
y[y.argmax()]=0
print("after max value replaced by 0:")
print(y)

original array:
[0.60078901 0.49819394 0.99773751 0.12507948 0.38972835 0.0303531
 0.09119668 0.9998607  0.19926842 0.02328607]
after max value replaced by 0:
[0.60078901 0.49819394 0.99773751 0.12507948 0.38972835 0.0303531
 0.09119668 0.         0.19926842 0.02328607]


# 9. How to print all the values of an array?

In [88]:
z=np.zeros((4,4))
print(z)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [98]:
s=np.array([[1,2,3,4],[5,6,7,8],[1,3,4,5]])
print("before subtraction:")
print(s)
t=s-s.mean(axis=1,keepdims=True)
print("after subtraction:")
print(t)

before subtraction:
[[1 2 3 4]
 [5 6 7 8]
 [1 3 4 5]]
after subtraction:
[[-1.5  -0.5   0.5   1.5 ]
 [-1.5  -0.5   0.5   1.5 ]
 [-2.25 -0.25  0.75  1.75]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [110]:
b=np.array([1,2,3,4,5,6,7,8])
b[2:]+=1
print(b)

[1 2 4 5 6 7 8 9]


# 12.How to get the diagonal of a dot product?

In [122]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
e=np.diagonal(c.dot(d))
print(e)

[19 50]


# 13.How to find the most frequent value in an array?

In [124]:
f=np.array([1,2,1,4,1,5,1,6])
print(f)
print("most frequent value in the array:")
print(np.bincount(f).argmax())

[1 2 1 4 1 5 1 6]
most frequent value in the array:
1


# 14.How to get the n largest values of an array

In [117]:
w=np.array([1,2,3,4,5,6,7,8])
print(w)
n=1
print(w[np.argsort(w)[-n:]])

[1 2 3 4 5 6 7 8]
[8]


# 15.How to create a record array from a regular array?

In [120]:
ar=np.array(['red','blue','green'])
ar1=np.array([1,2,3])
result=np.core.records.fromarrays([ar,ar1])
print(result[0])
print(result[1])
print(result[2])

('red', 1)
('blue', 2)
('green', 3)
